# Generated by Django 2.2.6 on 2019-10-05 08:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20191005_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('phone', models.CharField(default='', max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 13, 54, 26, 454386))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'owner'), ('Admin', 'admin'), ('Analyst', 'analyst'), ('GroupAdmin', 'groupadmin'), ('Instructor', 'instructor'), ('Employee', 'employee')], default='employee', max_length=50)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 13, 54, 26, 457378))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilerole',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profilerole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profilerole',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='profilerole',
            name='user',
        ),
        migrations.AlterField(
            model_name='group',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='users.Institute'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 13, 54, 26, 457378)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to='users.Institute'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 13, 54, 26, 455383)),
        ),
        migrations.DeleteModel(
            name='Corporate',
        ),
        migrations.DeleteModel(
            name='ProfileRole',
        ),
        migrations.AddField(
            model_name='profilegrouprole',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Group'),
        ),
        migrations.AddField(
            model_name='profilegrouprole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilegrouprole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
