# Generated by Django 2.2.6 on 2019-10-05 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191005_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 15, 44, 51, 973799)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 15, 44, 51, 970823)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 15, 44, 51, 971803)),
        ),
        migrations.AlterField(
            model_name='profilegrouprole',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 15, 44, 51, 974796)),
        ),
    ]
