# Generated by Django 2.2.6 on 2019-10-05 11:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20191005_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'admin'), ('Analyst', 'analyst'), ('GroupAdmin', 'groupadmin'), ('Instructor', 'instructor'), ('Employee', 'employee')], default='employee', max_length=50)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 16, 47, 36, 460615))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 16, 47, 36, 459618)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 16, 47, 36, 457622)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 16, 47, 36, 458620)),
        ),
        migrations.DeleteModel(
            name='ProfileGroupRole',
        ),
        migrations.AddField(
            model_name='profilerole',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Group'),
        ),
        migrations.AddField(
            model_name='profilerole',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilerole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
