# Generated by Django 2.2.6 on 2019-10-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191005_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 22, 52, 15, 660921)),
        ),
        migrations.AlterField(
            model_name='institute',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 22, 52, 15, 658925)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 22, 52, 15, 659927)),
        ),
        migrations.AlterField(
            model_name='profilerole',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 22, 52, 15, 661918)),
        ),
        migrations.AlterField(
            model_name='profilerole',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Analyst', 'analyst'), ('GroupAdmin', 'groupadmin'), ('Instructor', 'instructor'), ('Employee', 'employee')], default='employee', max_length=15),
        ),
    ]
