# Generated by Django 2.2.6 on 2019-10-05 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20191005_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('seen_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 22, 52, 15, 689757), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
