# Generated by Django 2.2.6 on 2019-10-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='uploads/Media/')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('access', models.CharField(choices=[('Public', '1'), ('Institute', '2'), ('Group', '3')], default='2', max_length=1)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 22, 52, 15, 663912), null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 22, 52, 15, 663912), null=True)),
            ],
        ),
    ]
